### ISSUE TITLE
Milestone 1 Functional Prototype

### ISSUE THREAD

**Issue by EvyAvila** [IAMColumbia/gp2portfoliogame-EvyAvila#3]
Proof of Concept include main mechanic:
- [x] Create visual prototypes
- [x] Create project
   - [x] Create auto-generated levels 
   - [x] Character movement

GitHub classroom:
- [x] Create Branch for POC
- [x] Build POC add source to src folder
- [x] Commit milesotne work to branch
- [x] Pull Branch back to Master
- [x] Add POC build to build folder
