### ISSUE TITLE
Milestone 2 Vertical Slice All Features Submitted for testing

### ISSUE THREAD

**Issue by EvyAvila** [IAMColumbia/gp2portfoliogame-EvyAvila#4]
- [x] Create Branch for VS
- [x]  Work on VS
   - [x] Add Enemies
   - [x] Add function to earn disguises
   - [x] Expand level
   - [x] Create ending states 
- [x] Commit milestone work to branch
- [x] Pull VS back to Master
- [x] Add VS build to build folder
