### ISSUE TITLE
Milestone 3 MVP First Build

### ISSUE THREAD

**Issue by EvyAvila** [IAMColumbia/gp2portfoliogame-EvyAvila#5]
- [x] Create Branch for 1B
- [ ] Build 1B add source to src folder
- [ ] Commit milestone work to branch
- [ ] Pull Branch back to Master
- [ ] Add 1B build to build folder
- [ ] MVP Playtest In canvas
 
- [x] Update Input System
- [x] Add Interface
- [x] Expand Level
- [x] Update Enemy characters
