### ISSUE TITLE
Milestone 4 Final Build

### ISSUE THREAD

**Issue by EvyAvila** [IAMColumbia/gp2portfoliogame-EvyAvila#6]
- [ ] Create Branch for FB
- [ ] Build FB add source to src folder
- [ ] Commit milestone work to branch
- [ ] Pull Branch back to Master
- [ ] Add FB build to build folder
- [ ] Final Build Playtest In canvas
